### ISSUE TITLE
maknz/slack doesn't support Laravel 5.4

### ISSUE THREAD

**Issue by Mopster** [TeraDox/Notify-Laravel#9]
Looks like `maknz/slack` doesn't support Laravel 5.4 and is no longer actively maintained. Checking the repository, the author added `Note: this package is no longer being actively maintained.` about 10 days ago.

Getting the following error : 

```
 [Symfony\Component\Debug\Exception\FatalErrorException]            
 Call to undefined method Illuminate\Foundation\Application::share()
```
```
[2017-03-06 15:14:25] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::share()' in C:\laragon\www\broadsoft\vendor\maknz\slack\src\SlackServiceProviderLaravel5.php:27
```

I see a few forks that fix the 5.4 issue.

**Comment by rikeda001** [comment]
Thanks for the information! Since they do not have time to maintain the package (https://github.com/maknz/slack/issues/82), we created customized SlackServiceProvider class that is simply changed share() to singleton().
We are planning to fork the package if other issue happens.

To use the customized Service Provider, please change 
```Maknz\Slack\SlackServiceProvider::class``` 
to 
```Notify\Laravel\SlackServiceProvider::class```
for 'provider' in config/app.php.

Let me know if other issue happens.

**Comment by IvandaNothabeer** [comment]
https://github.com/alek13/slack
